/**
 * Ícones Font Awesome 5 (classes completas) — alinhado a @fortawesome/fontawesome-free@5.
 * Uso: [icon]="SigIcons.health" ou icon="fas fa-laptop"
 */
export const SigIcons = {
  health: 'fas fa-heartbeat',
  assets: 'fas fa-laptop',
  cost: 'fas fa-coins',
  domain: 'fas fa-globe',
  license: 'fas fa-key',
  alert: 'fas fa-bell',
  alertCritical: 'fas fa-exclamation-circle',
  warning: 'fas fa-exclamation-triangle',
  info: 'fas fa-info-circle',
  success: 'fas fa-check-circle',
  pending: 'fas fa-clock',
  overdue: 'fas fa-calendar-times',
  access: 'fas fa-unlock-alt',
  chart: 'fas fa-chart-line',
  chartPie: 'fas fa-chart-pie',
  refresh: 'fas fa-sync-alt',
  check: 'fas fa-check',
  close: 'fas fa-times',
  trash: 'fas fa-trash-alt',
  budget: 'fas fa-wallet',
  savings: 'fas fa-piggy-bank',
  tasks: 'fas fa-tasks',
  tasksDone: 'fas fa-clipboard-check',
  search: 'fas fa-search',
  import: 'fas fa-file-upload',
  export: 'fas fa-file-download',
  plus: 'fas fa-plus',
  building: 'fas fa-building',
  server: 'fas fa-server',
  shield: 'fas fa-shield-alt',
  wrench: 'fas fa-wrench',
  box: 'fas fa-cubes',
  external: 'fas fa-external-link-alt',
  eye: 'fas fa-eye',
  pencil: 'fas fa-pen',
  chevronLeft: 'fas fa-chevron-left',
  chevronRight: 'fas fa-chevron-right',
} as const;

export type SigIconClass = (typeof SigIcons)[keyof typeof SigIcons];
