/** Tabelas `public` expostas pela API (leitura + escrita genérica). */
export const API_TABLES = new Set([
  'organizations',
  'empresas',
  'departamentos',
  'usuarios',
  'profiles',
  'user_roles',
  'ativos',
  'dominios',
  'dns_records',
  'licencas',
  'servidores',
  'contratos',
  'manutencoes',
  'movimentacoes',
  'inventario',
  'inventario_movimentacoes',
  'alertas',
  'orcamentos',
  'acoes_economista',
  'registros_acesso',
  'riscos',
  'pagamentos',
  'termos_responsabilidade',
]);
